/*
* Autogenerated by rules_parser.py
*
* DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*
*/

#include "S100RulesParser/ChooseRule.h"
#include "S100RulesParser/private/GenRules.h"

S101RULES_API void ChooseRule(IObjectDrawer *object_drawer, int class_id, int index_feature) {
    switch (class_id) {
        case ClassCodes::idAdministrationArea:
            DrawAdministrationArea(object_drawer, index_feature);
            break;
        case ClassCodes::idAirportAirfield:
            DrawAirportAirfield(object_drawer, index_feature);
            break;
        case ClassCodes::idAnchorBerth:
            DrawAnchorBerth(object_drawer, index_feature);
            break;
        case ClassCodes::idAnchorageArea:
            DrawAnchorageArea(object_drawer, index_feature);
            break;
        case ClassCodes::idArchipelagicSeaLaneAxis:
            DrawArchipelagicSeaLaneAxis(object_drawer, index_feature);
            break;
        case ClassCodes::idArchipelagicSeaLane:
            DrawArchipelagicSeaLane(object_drawer, index_feature);
            break;
        case ClassCodes::idBeaconCardinal:
            DrawBeaconCardinal(object_drawer, index_feature);
            break;
        case ClassCodes::idBeaconIsolatedDanger:
            DrawBeaconIsolatedDanger(object_drawer, index_feature);
            break;
        case ClassCodes::idBeaconLateral:
            DrawBeaconLateral(object_drawer, index_feature);
            break;
        case ClassCodes::idBeaconSafeWater:
            DrawBeaconSafeWater(object_drawer, index_feature);
            break;
        case ClassCodes::idBeaconSpecialPurposeGeneral:
            DrawBeaconSpecialPurposeGeneral(object_drawer, index_feature);
            break;
        case ClassCodes::idBerth:
            DrawBerth(object_drawer, index_feature);
            break;
        case ClassCodes::idBridge:
            DrawBridge(object_drawer, index_feature);
            break;
        case ClassCodes::idBuilding:
            DrawBuilding(object_drawer, index_feature);
            break;
        case ClassCodes::idBuiltUpArea:
            DrawBuiltUpArea(object_drawer, index_feature);
            break;
        case ClassCodes::idBuoyCardinal:
            DrawBuoyCardinal(object_drawer, index_feature);
            break;
        case ClassCodes::idBuoyInstallation:
            DrawBuoyInstallation(object_drawer, index_feature);
            break;
        case ClassCodes::idBuoyIsolatedDanger:
            DrawBuoyIsolatedDanger(object_drawer, index_feature);
            break;
        case ClassCodes::idBuoyLateral:
            DrawBuoyLateral(object_drawer, index_feature);
            break;
        case ClassCodes::idBuoySafeWater:
            DrawBuoySafeWater(object_drawer, index_feature);
            break;
        case ClassCodes::idBuoySpecialPurposeGeneral:
            DrawBuoySpecialPurposeGeneral(object_drawer, index_feature);
            break;
        case ClassCodes::idCableArea:
            DrawCableArea(object_drawer, index_feature);
            break;
        case ClassCodes::idCableOverhead:
            DrawCableOverhead(object_drawer, index_feature);
            break;
        case ClassCodes::idCableSubmarine:
            DrawCableSubmarine(object_drawer, index_feature);
            break;
        case ClassCodes::idCanal:
            DrawCanal(object_drawer, index_feature);
            break;
        case ClassCodes::idCargoTranshipmentArea:
            DrawCargoTranshipmentArea(object_drawer, index_feature);
            break;
        case ClassCodes::idCauseway:
            DrawCauseway(object_drawer, index_feature);
            break;
        case ClassCodes::idCautionArea:
            DrawCautionArea(object_drawer, index_feature);
            break;
        case ClassCodes::idCheckpoint:
            DrawCheckpoint(object_drawer, index_feature);
            break;
        case ClassCodes::idCoastguardStation:
            DrawCoastguardStation(object_drawer, index_feature);
            break;
        case ClassCodes::idCoastline:
            DrawCoastline(object_drawer, index_feature);
            break;
        case ClassCodes::idContiguousZone:
            DrawContiguousZone(object_drawer, index_feature);
            break;
        case ClassCodes::idContinentalShelfArea:
            DrawContinentalShelfArea(object_drawer, index_feature);
            break;
        case ClassCodes::idConveyor:
            DrawConveyor(object_drawer, index_feature);
            break;
        case ClassCodes::idCrane:
            DrawCrane(object_drawer, index_feature);
            break;
        case ClassCodes::idCurrentNonGravitational:
            DrawCurrentNonGravitational(object_drawer, index_feature);
            break;
        case ClassCodes::idCustomZone:
            DrawCustomZone(object_drawer, index_feature);
            break;
        case ClassCodes::idDam:
            DrawDam(object_drawer, index_feature);
            break;
        case ClassCodes::idDataCoverage:
            DrawDataCoverage(object_drawer, index_feature);
            break;
        case ClassCodes::idDeepWaterRoutePart:
            DrawDeepWaterRoutePart(object_drawer, index_feature);
            break;
        case ClassCodes::idDepthArea:
            DrawDepthArea(object_drawer, index_feature);
            break;
        case ClassCodes::idDepthContour:
            DrawDepthContour(object_drawer, index_feature);
            break;
        case ClassCodes::idDistanceMark:
            DrawDistanceMark(object_drawer, index_feature);
            break;
        case ClassCodes::idDockArea:
            DrawDockArea(object_drawer, index_feature);
            break;
        case ClassCodes::idDredgedArea:
            DrawDredgedArea(object_drawer, index_feature);
            break;
        case ClassCodes::idDryDock:
            DrawDryDock(object_drawer, index_feature);
            break;
        case ClassCodes::idDyke:
            DrawDyke(object_drawer, index_feature);
            break;
        case ClassCodes::idExclusiveEconomicZone:
            DrawExclusiveEconomicZone(object_drawer, index_feature);
            break;
        case ClassCodes::idFairway:
            DrawFairway(object_drawer, index_feature);
            break;
        case ClassCodes::idFenceWall:
            DrawFenceWall(object_drawer, index_feature);
            break;
        case ClassCodes::idFerryRoute:
            DrawFerryRoute(object_drawer, index_feature);
            break;
        case ClassCodes::idFisheryZone:
            DrawFisheryZone(object_drawer, index_feature);
            break;
        case ClassCodes::idFishingFacility:
            DrawFishingFacility(object_drawer, index_feature);
            break;
        case ClassCodes::idFishingGround:
            DrawFishingGround(object_drawer, index_feature);
            break;
        case ClassCodes::idFloatingDock:
            DrawFloatingDock(object_drawer, index_feature);
            break;
        case ClassCodes::idFogSignal:
            DrawFogSignal(object_drawer, index_feature);
            break;
        case ClassCodes::idFortifiedStructure:
            DrawFortifiedStructure(object_drawer, index_feature);
            break;
        case ClassCodes::idFoulGround:
            DrawFoulGround(object_drawer, index_feature);
            break;
        case ClassCodes::idFreePortArea:
            DrawFreePortArea(object_drawer, index_feature);
            break;
        case ClassCodes::idGate:
            DrawGate(object_drawer, index_feature);
            break;
        case ClassCodes::idGridiron:
            DrawGridiron(object_drawer, index_feature);
            break;
        case ClassCodes::idHarbourAreaAdministrative:
            DrawHarbourAreaAdministrative(object_drawer, index_feature);
            break;
        case ClassCodes::idHarbourFacility:
            DrawHarbourFacility(object_drawer, index_feature);
            break;
        case ClassCodes::idHulk:
            DrawHulk(object_drawer, index_feature);
            break;
        case ClassCodes::idIceArea:
            DrawIceArea(object_drawer, index_feature);
            break;
        case ClassCodes::idInshoreTrafficZone:
            DrawInshoreTrafficZone(object_drawer, index_feature);
            break;
        case ClassCodes::idLake:
            DrawLake(object_drawer, index_feature);
            break;
        case ClassCodes::idLandArea:
            DrawLandArea(object_drawer, index_feature);
            break;
        case ClassCodes::idLandElevation:
            DrawLandElevation(object_drawer, index_feature);
            break;
        case ClassCodes::idLandRegion:
            DrawLandRegion(object_drawer, index_feature);
            break;
        case ClassCodes::idLandmark:
            DrawLandmark(object_drawer, index_feature);
            break;
        case ClassCodes::idLightFloat:
            DrawLightFloat(object_drawer, index_feature);
            break;
        case ClassCodes::idLightSectored:
            DrawLightSectored(object_drawer, index_feature);
            break;
        case ClassCodes::idLightVessel:
            DrawLightVessel(object_drawer, index_feature);
            break;
        case ClassCodes::idLocalDirectionOfBuoyage:
            DrawLocalDirectionOfBuoyage(object_drawer, index_feature);
            break;
        case ClassCodes::idLocalMagneticAnomaly:
            DrawLocalMagneticAnomaly(object_drawer, index_feature);
            break;
        case ClassCodes::idLockBasin:
            DrawLockBasin(object_drawer, index_feature);
            break;
        case ClassCodes::idLogPond:
            DrawLogPond(object_drawer, index_feature);
            break;
        case ClassCodes::idMagneticVariation:
            DrawMagneticVariation(object_drawer, index_feature);
            break;
        case ClassCodes::idMarineFarmCulture:
            DrawMarineFarmCulture(object_drawer, index_feature);
            break;
        case ClassCodes::idMilitaryPracticeArea:
            DrawMilitaryPracticeArea(object_drawer, index_feature);
            break;
        case ClassCodes::idMooringWarpingFacility:
            DrawMooringWarpingFacility(object_drawer, index_feature);
            break;
        case ClassCodes::idNavigationLine:
            DrawNavigationLine(object_drawer, index_feature);
            break;
        case ClassCodes::idNavigationalSystemOfMarks:
            DrawNavigationalSystemOfMarks(object_drawer, index_feature);
            break;
        case ClassCodes::idObstruction:
            DrawObstruction(object_drawer, index_feature);
            break;
        case ClassCodes::idOffshorePlatform:
            DrawOffshorePlatform(object_drawer, index_feature);
            break;
        case ClassCodes::idOffshoreProductionArea:
            DrawOffshoreProductionArea(object_drawer, index_feature);
            break;
        case ClassCodes::idOilBarrier:
            DrawOilBarrier(object_drawer, index_feature);
            break;
        case ClassCodes::idPile:
            DrawPile(object_drawer, index_feature);
            break;
        case ClassCodes::idPilotBoardingPlace:
            DrawPilotBoardingPlace(object_drawer, index_feature);
            break;
        case ClassCodes::idPipelineOverhead:
            DrawPipelineOverhead(object_drawer, index_feature);
            break;
        case ClassCodes::idPipelineSubmarineOnLand:
            DrawPipelineSubmarineOnLand(object_drawer, index_feature);
            break;
        case ClassCodes::idPontoon:
            DrawPontoon(object_drawer, index_feature);
            break;
        case ClassCodes::idPrecautionaryArea:
            DrawPrecautionaryArea(object_drawer, index_feature);
            break;
        case ClassCodes::idProductionStorageArea:
            DrawProductionStorageArea(object_drawer, index_feature);
            break;
        case ClassCodes::idPylonBridgeSupport:
            DrawPylonBridgeSupport(object_drawer, index_feature);
            break;
        case ClassCodes::idRadarLine:
            DrawRadarLine(object_drawer, index_feature);
            break;
        case ClassCodes::idRadarRange:
            DrawRadarRange(object_drawer, index_feature);
            break;
        case ClassCodes::idRadarReflector:
            DrawRadarReflector(object_drawer, index_feature);
            break;
        case ClassCodes::idRadarStation:
            DrawRadarStation(object_drawer, index_feature);
            break;
        case ClassCodes::idRadarTransponderBeacon:
            DrawRadarTransponderBeacon(object_drawer, index_feature);
            break;
        case ClassCodes::idRadioCallingInPoint:
            DrawRadioCallingInPoint(object_drawer, index_feature);
            break;
        case ClassCodes::idRadioStation:
            DrawRadioStation(object_drawer, index_feature);
            break;
        case ClassCodes::idRailway:
            DrawRailway(object_drawer, index_feature);
            break;
        case ClassCodes::idRapids:
            DrawRapids(object_drawer, index_feature);
            break;
        case ClassCodes::idRecommendedRouteCentreline:
            DrawRecommendedRouteCentreline(object_drawer, index_feature);
            break;
        case ClassCodes::idRecommendedTrack:
            DrawRecommendedTrack(object_drawer, index_feature);
            break;
        case ClassCodes::idRecommendedTrafficLanePart:
            DrawRecommendedTrafficLanePart(object_drawer, index_feature);
            break;
        case ClassCodes::idRescueStation:
            DrawRescueStation(object_drawer, index_feature);
            break;
        case ClassCodes::idRiver:
            DrawRiver(object_drawer, index_feature);
            break;
        case ClassCodes::idRoad:
            DrawRoad(object_drawer, index_feature);
            break;
        case ClassCodes::idRunway:
            DrawRunway(object_drawer, index_feature);
            break;
        case ClassCodes::idSandwave:
            DrawSandwave(object_drawer, index_feature);
            break;
        case ClassCodes::idSeaAreaNamedWaterArea:
            DrawSeaAreaNamedWaterArea(object_drawer, index_feature);
            break;
        case ClassCodes::idSeabedArea:
            DrawSeabedArea(object_drawer, index_feature);
            break;
        case ClassCodes::idSeaplaneLandingArea:
            DrawSeaplaneLandingArea(object_drawer, index_feature);
            break;
        case ClassCodes::idShorelineConstruction:
            DrawShorelineConstruction(object_drawer, index_feature);
            break;
        case ClassCodes::idSignalStationTraffic:
            DrawSignalStationTraffic(object_drawer, index_feature);
            break;
        case ClassCodes::idSignalStationWarning:
            DrawSignalStationWarning(object_drawer, index_feature);
            break;
        case ClassCodes::idSiloTank:
            DrawSiloTank(object_drawer, index_feature);
            break;
        case ClassCodes::idSlopeTopline:
            DrawSlopeTopline(object_drawer, index_feature);
            break;
        case ClassCodes::idSlopingGround:
            DrawSlopingGround(object_drawer, index_feature);
            break;
        case ClassCodes::idSmallCraftFacility:
            DrawSmallCraftFacility(object_drawer, index_feature);
            break;
        case ClassCodes::idSoundingDatum:
            DrawSoundingDatum(object_drawer, index_feature);
            break;
        case ClassCodes::idSounding:
            DrawSounding(object_drawer, index_feature);
            break;
        case ClassCodes::idSpring:
            DrawSpring(object_drawer, index_feature);
            break;
        case ClassCodes::idStraightTerritorialSeaBaseline:
            DrawStraightTerritorialSeaBaseline(object_drawer, index_feature);
            break;
        case ClassCodes::idSubmarinePipelineArea:
            DrawSubmarinePipelineArea(object_drawer, index_feature);
            break;
        case ClassCodes::idSubmarineTransitLane:
            DrawSubmarineTransitLane(object_drawer, index_feature);
            break;
        case ClassCodes::idSweptArea:
            DrawSweptArea(object_drawer, index_feature);
            break;
        case ClassCodes::idTerritorialSeaArea:
            DrawTerritorialSeaArea(object_drawer, index_feature);
            break;
        case ClassCodes::idTidalStreamFloodEbb:
            DrawTidalStreamFloodEbb(object_drawer, index_feature);
            break;
        case ClassCodes::idTidalStreamPanelData:
            DrawTidalStreamPanelData(object_drawer, index_feature);
            break;
        case ClassCodes::idTideway:
            DrawTideway(object_drawer, index_feature);
            break;
        case ClassCodes::idTrafficSeparationLine:
            DrawTrafficSeparationLine(object_drawer, index_feature);
            break;
        case ClassCodes::idTrafficSeparationSchemeBoundary:
            DrawTrafficSeparationSchemeBoundary(object_drawer, index_feature);
            break;
        case ClassCodes::idTrafficSeparationSchemeCrossing:
            DrawTrafficSeparationSchemeCrossing(object_drawer, index_feature);
            break;
        case ClassCodes::idTrafficSeparationSchemeLanePart:
            DrawTrafficSeparationSchemeLanePart(object_drawer, index_feature);
            break;
        case ClassCodes::idTrafficSeparationSchemeRoundabout:
            DrawTrafficSeparationSchemeRoundabout(object_drawer, index_feature);
            break;
        case ClassCodes::idTrafficSeparationZone:
            DrawTrafficSeparationZone(object_drawer, index_feature);
            break;
        case ClassCodes::idTunnel:
            DrawTunnel(object_drawer, index_feature);
            break;
        case ClassCodes::idTwoWayRoutePart:
            DrawTwoWayRoutePart(object_drawer, index_feature);
            break;
        case ClassCodes::idUnsurveyedArea:
            DrawUnsurveyedArea(object_drawer, index_feature);
            break;
        case ClassCodes::idVegetation:
            DrawVegetation(object_drawer, index_feature);
            break;
        case ClassCodes::idWaterTurbulence:
            DrawWaterTurbulence(object_drawer, index_feature);
            break;
        case ClassCodes::idWaterfall:
            DrawWaterfall(object_drawer, index_feature);
            break;
        case ClassCodes::idWeedKelp:
            DrawWeedKelp(object_drawer, index_feature);
            break;
        case ClassCodes::idWreck:
            DrawWreck(object_drawer, index_feature);
            break;
        default:
            break;
    }
}