#pragma once
/*
* Autogenerated by rules_parser.py
*
* DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*
*/

#include "stdlib.h"
#include "src/IObjectDrawer.h"

void DrawAdministrationArea(IObjectDrawer *object_drawer, int index_feature);

void DrawAirportAirfield(IObjectDrawer *object_drawer, int index_feature);

void DrawAnchorBerth(IObjectDrawer *object_drawer, int index_feature);

void DrawAnchorageArea(IObjectDrawer *object_drawer, int index_feature);

void DrawArchipelagicSeaLaneAxis(IObjectDrawer *object_drawer, int index_feature);

void DrawArchipelagicSeaLane(IObjectDrawer *object_drawer, int index_feature);

void DrawBeaconCardinal(IObjectDrawer *object_drawer, int index_feature);

void DrawBeaconIsolatedDanger(IObjectDrawer *object_drawer, int index_feature);

void DrawBeaconLateral(IObjectDrawer *object_drawer, int index_feature);

void DrawBeaconSafeWater(IObjectDrawer *object_drawer, int index_feature);

void DrawBeaconSpecialPurposeGeneral(IObjectDrawer *object_drawer, int index_feature);

void DrawBerth(IObjectDrawer *object_drawer, int index_feature);

void DrawBridge(IObjectDrawer *object_drawer, int index_feature);

void DrawBuilding(IObjectDrawer *object_drawer, int index_feature);

void DrawBuiltUpArea(IObjectDrawer *object_drawer, int index_feature);

void DrawBuoyCardinal(IObjectDrawer *object_drawer, int index_feature);

void DrawBuoyInstallation(IObjectDrawer *object_drawer, int index_feature);

void DrawBuoyIsolatedDanger(IObjectDrawer *object_drawer, int index_feature);

void DrawBuoyLateral(IObjectDrawer *object_drawer, int index_feature);

void DrawBuoySafeWater(IObjectDrawer *object_drawer, int index_feature);

void DrawBuoySpecialPurposeGeneral(IObjectDrawer *object_drawer, int index_feature);

void DrawCableArea(IObjectDrawer *object_drawer, int index_feature);

void DrawCableOverhead(IObjectDrawer *object_drawer, int index_feature);

void DrawCableSubmarine(IObjectDrawer *object_drawer, int index_feature);

void DrawCanal(IObjectDrawer *object_drawer, int index_feature);

void DrawCargoTranshipmentArea(IObjectDrawer *object_drawer, int index_feature);

void DrawCauseway(IObjectDrawer *object_drawer, int index_feature);

void DrawCautionArea(IObjectDrawer *object_drawer, int index_feature);

void DrawCheckpoint(IObjectDrawer *object_drawer, int index_feature);

void DrawCoastguardStation(IObjectDrawer *object_drawer, int index_feature);

void DrawCoastline(IObjectDrawer *object_drawer, int index_feature);

void DrawContiguousZone(IObjectDrawer *object_drawer, int index_feature);

void DrawContinentalShelfArea(IObjectDrawer *object_drawer, int index_feature);

void DrawConveyor(IObjectDrawer *object_drawer, int index_feature);

void DrawCrane(IObjectDrawer *object_drawer, int index_feature);

void DrawCurrentNonGravitational(IObjectDrawer *object_drawer, int index_feature);

void DrawCustomZone(IObjectDrawer *object_drawer, int index_feature);

void DrawDam(IObjectDrawer *object_drawer, int index_feature);

void DrawDataCoverage(IObjectDrawer *object_drawer, int index_feature);

void DrawDeepWaterRoutePart(IObjectDrawer *object_drawer, int index_feature);

void DrawDepthArea(IObjectDrawer *object_drawer, int index_feature);

void DrawDepthContour(IObjectDrawer *object_drawer, int index_feature);

void DrawDistanceMark(IObjectDrawer *object_drawer, int index_feature);

void DrawDockArea(IObjectDrawer *object_drawer, int index_feature);

void DrawDredgedArea(IObjectDrawer *object_drawer, int index_feature);

void DrawDryDock(IObjectDrawer *object_drawer, int index_feature);

void DrawDyke(IObjectDrawer *object_drawer, int index_feature);

void DrawExclusiveEconomicZone(IObjectDrawer *object_drawer, int index_feature);

void DrawFairway(IObjectDrawer *object_drawer, int index_feature);

void DrawFenceWall(IObjectDrawer *object_drawer, int index_feature);

void DrawFerryRoute(IObjectDrawer *object_drawer, int index_feature);

void DrawFisheryZone(IObjectDrawer *object_drawer, int index_feature);

void DrawFishingFacility(IObjectDrawer *object_drawer, int index_feature);

void DrawFishingGround(IObjectDrawer *object_drawer, int index_feature);

void DrawFloatingDock(IObjectDrawer *object_drawer, int index_feature);

void DrawFogSignal(IObjectDrawer *object_drawer, int index_feature);

void DrawFortifiedStructure(IObjectDrawer *object_drawer, int index_feature);

void DrawFoulGround(IObjectDrawer *object_drawer, int index_feature);

void DrawFreePortArea(IObjectDrawer *object_drawer, int index_feature);

void DrawGate(IObjectDrawer *object_drawer, int index_feature);

void DrawGridiron(IObjectDrawer *object_drawer, int index_feature);

void DrawHarbourAreaAdministrative(IObjectDrawer *object_drawer, int index_feature);

void DrawHarbourFacility(IObjectDrawer *object_drawer, int index_feature);

void DrawHulk(IObjectDrawer *object_drawer, int index_feature);

void DrawIceArea(IObjectDrawer *object_drawer, int index_feature);

void DrawInshoreTrafficZone(IObjectDrawer *object_drawer, int index_feature);

void DrawLake(IObjectDrawer *object_drawer, int index_feature);

void DrawLandArea(IObjectDrawer *object_drawer, int index_feature);

void DrawLandElevation(IObjectDrawer *object_drawer, int index_feature);

void DrawLandRegion(IObjectDrawer *object_drawer, int index_feature);

void DrawLandmark(IObjectDrawer *object_drawer, int index_feature);

void DrawLightFloat(IObjectDrawer *object_drawer, int index_feature);

void DrawLightSectored(IObjectDrawer *object_drawer, int index_feature);

void DrawLightVessel(IObjectDrawer *object_drawer, int index_feature);

void DrawLocalDirectionOfBuoyage(IObjectDrawer *object_drawer, int index_feature);

void DrawLocalMagneticAnomaly(IObjectDrawer *object_drawer, int index_feature);

void DrawLockBasin(IObjectDrawer *object_drawer, int index_feature);

void DrawLogPond(IObjectDrawer *object_drawer, int index_feature);

void DrawMagneticVariation(IObjectDrawer *object_drawer, int index_feature);

void DrawMarineFarmCulture(IObjectDrawer *object_drawer, int index_feature);

void DrawMilitaryPracticeArea(IObjectDrawer *object_drawer, int index_feature);

void DrawMooringWarpingFacility(IObjectDrawer *object_drawer, int index_feature);

void DrawNavigationLine(IObjectDrawer *object_drawer, int index_feature);

void DrawNavigationalSystemOfMarks(IObjectDrawer *object_drawer, int index_feature);

void DrawObstruction(IObjectDrawer *object_drawer, int index_feature);

void DrawOffshorePlatform(IObjectDrawer *object_drawer, int index_feature);

void DrawOffshoreProductionArea(IObjectDrawer *object_drawer, int index_feature);

void DrawOilBarrier(IObjectDrawer *object_drawer, int index_feature);

void DrawPile(IObjectDrawer *object_drawer, int index_feature);

void DrawPilotBoardingPlace(IObjectDrawer *object_drawer, int index_feature);

void DrawPipelineOverhead(IObjectDrawer *object_drawer, int index_feature);

void DrawPipelineSubmarineOnLand(IObjectDrawer *object_drawer, int index_feature);

void DrawPontoon(IObjectDrawer *object_drawer, int index_feature);

void DrawPrecautionaryArea(IObjectDrawer *object_drawer, int index_feature);

void DrawProductionStorageArea(IObjectDrawer *object_drawer, int index_feature);

void DrawPylonBridgeSupport(IObjectDrawer *object_drawer, int index_feature);

void DrawRadarLine(IObjectDrawer *object_drawer, int index_feature);

void DrawRadarRange(IObjectDrawer *object_drawer, int index_feature);

void DrawRadarReflector(IObjectDrawer *object_drawer, int index_feature);

void DrawRadarStation(IObjectDrawer *object_drawer, int index_feature);

void DrawRadarTransponderBeacon(IObjectDrawer *object_drawer, int index_feature);

void DrawRadioCallingInPoint(IObjectDrawer *object_drawer, int index_feature);

void DrawRadioStation(IObjectDrawer *object_drawer, int index_feature);

void DrawRailway(IObjectDrawer *object_drawer, int index_feature);

void DrawRapids(IObjectDrawer *object_drawer, int index_feature);

void DrawRecommendedRouteCentreline(IObjectDrawer *object_drawer, int index_feature);

void DrawRecommendedTrack(IObjectDrawer *object_drawer, int index_feature);

void DrawRecommendedTrafficLanePart(IObjectDrawer *object_drawer, int index_feature);

void DrawRescueStation(IObjectDrawer *object_drawer, int index_feature);

void DrawRiver(IObjectDrawer *object_drawer, int index_feature);

void DrawRoad(IObjectDrawer *object_drawer, int index_feature);

void DrawRunway(IObjectDrawer *object_drawer, int index_feature);

void DrawSandwave(IObjectDrawer *object_drawer, int index_feature);

void DrawSeaAreaNamedWaterArea(IObjectDrawer *object_drawer, int index_feature);

void DrawSeabedArea(IObjectDrawer *object_drawer, int index_feature);

void DrawSeaplaneLandingArea(IObjectDrawer *object_drawer, int index_feature);

void DrawShorelineConstruction(IObjectDrawer *object_drawer, int index_feature);

void DrawSignalStationTraffic(IObjectDrawer *object_drawer, int index_feature);

void DrawSignalStationWarning(IObjectDrawer *object_drawer, int index_feature);

void DrawSiloTank(IObjectDrawer *object_drawer, int index_feature);

void DrawSlopeTopline(IObjectDrawer *object_drawer, int index_feature);

void DrawSlopingGround(IObjectDrawer *object_drawer, int index_feature);

void DrawSmallCraftFacility(IObjectDrawer *object_drawer, int index_feature);

void DrawSoundingDatum(IObjectDrawer *object_drawer, int index_feature);

void DrawSounding(IObjectDrawer *object_drawer, int index_feature);

void DrawSpring(IObjectDrawer *object_drawer, int index_feature);

void DrawStraightTerritorialSeaBaseline(IObjectDrawer *object_drawer, int index_feature);

void DrawSubmarinePipelineArea(IObjectDrawer *object_drawer, int index_feature);

void DrawSubmarineTransitLane(IObjectDrawer *object_drawer, int index_feature);

void DrawSweptArea(IObjectDrawer *object_drawer, int index_feature);

void DrawTerritorialSeaArea(IObjectDrawer *object_drawer, int index_feature);

void DrawTidalStreamFloodEbb(IObjectDrawer *object_drawer, int index_feature);

void DrawTidalStreamPanelData(IObjectDrawer *object_drawer, int index_feature);

void DrawTideway(IObjectDrawer *object_drawer, int index_feature);

void DrawTrafficSeparationLine(IObjectDrawer *object_drawer, int index_feature);

void DrawTrafficSeparationSchemeBoundary(IObjectDrawer *object_drawer, int index_feature);

void DrawTrafficSeparationSchemeCrossing(IObjectDrawer *object_drawer, int index_feature);

void DrawTrafficSeparationSchemeLanePart(IObjectDrawer *object_drawer, int index_feature);

void DrawTrafficSeparationSchemeRoundabout(IObjectDrawer *object_drawer, int index_feature);

void DrawTrafficSeparationZone(IObjectDrawer *object_drawer, int index_feature);

void DrawTunnel(IObjectDrawer *object_drawer, int index_feature);

void DrawTwoWayRoutePart(IObjectDrawer *object_drawer, int index_feature);

void DrawUnsurveyedArea(IObjectDrawer *object_drawer, int index_feature);

void DrawVegetation(IObjectDrawer *object_drawer, int index_feature);

void DrawWaterTurbulence(IObjectDrawer *object_drawer, int index_feature);

void DrawWaterfall(IObjectDrawer *object_drawer, int index_feature);

void DrawWeedKelp(IObjectDrawer *object_drawer, int index_feature);

void DrawWreck(IObjectDrawer *object_drawer, int index_feature);
