#pragma once

#include <map>
#include <string>
#include <utility>
/*
* Autogenerated by rules_parser.py
*
* DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*
*/

namespace S101Symbols {
    struct Symbol {
        int NumSymbol;
        double OffsetX;
        double OffsetY;
        std::string NameSymbol;
    };

    std::map<std::string, Symbol> &Symbols();

    std::map<int, Symbol> &SymbolsById();
}
namespace S101Colors {
    struct Color {
        int R, G, B;
        std::string NameColor;
    };

    std::map<std::string, Color> &Colors();
}